### ISSUE TITLE
Code coverage inaccurate

### ISSUE THREAD

**Issue by penx** [penx/govuk-react#95]
After moving to a monorepo, the code coverage report is not working correctly.

This is because:

- package A relies on package B
- package A includes unit tests that use code from package B so should be included in codecov
- package A uses /lib folder from package B due to being a package dependency rather than relative path
- tests on /lib folder in package B don't count as code coverage on the src folder.

Perhaps we should be ensuring code coverage for a package is 100% solely using unit tests within that package, however for e.g. the constants package I'm not sure how we would do this.

**Comment by stevesims** [comment]
it feels to me that coverage reports should cover only the package to which they relate

so if package A has tests that use code from package B, then we should be able to set up the coverage so that only the files within package A are being checked for coverage, and the import from package B should get ignored

package B would still have it's own unit tests and coverage of it's own code

not sure about constants package TBH

**Comment by penx** [comment]
Should be fixed by #102, #103 and #104
